#!/bin/bash

VERSION=$(git ls-remote --tags -q https://github.com/rspamd/rspamd | sed -n "s/^[[:xdigit:]]\{40\}[[:blank:]]refs\/tags\/\([0-9]\{1\}\.[0-9]\{1,2\}\($\|\.[0-9]\{1,2\}$\)\)/\1/p" | sort --version-sort | tail -1)

docker tag \
	"${IMAGE_NAME}" \
	"${DOCKER_REPO}:${VERSION}"
docker push \
	"${DOCKER_REPO}:${VERSION}"
