#!/bin/bash

VERSION=$(git ls-remote --refs --tags --sort="v:refname" https://github.com/rspamd/rspamd | tail -n1 | sed 's/.*\///')

docker tag \
	"${IMAGE_NAME}" \
	"${DOCKER_REPO}:${VERSION}"
docker push \
	"${DOCKER_REPO}:${VERSION}"
